#!/usr/bin/python3
#
# Created by: hodorsec
# Description:
# Used to print from and until certain given lines. Uses "from","to" and "file" as an argument
#
import sys
import os

# Main
if __name__ == '__main__':
    # Check for given arguments
    if len(sys.argv) == 4:
        filen = sys.argv[1]
        read_from = int(sys.argv[2])-1
        read_to = int(sys.argv[3])
    else:
        print("[*] Usage: " + sys.argv[0] + " <filename> <from> <to>")
        print("[*] Example: " + sys.argv[0] + " /etc/passwd 2 10\n")
        exit(0)

    if os.path.isfile(filen):
        try:
            with open(filen,'r') as f:
                lines = f.readlines()
            lines_to_read = [read_from,read_to]        

            for pos,line in enumerate(lines):
                if pos in range(read_from,read_to):
                    print(str(pos+1) + "\t" + line,end="")
        except KeyboardInterrupt:
                print("\n\n[!] User requested an interrupt, exiting...\n")
                exit(0)
        except:
            pass
